pin @bufbuild/protobuf at last working version
version 1.7.2 seems to work.
version 1.8.0 could not issue a seek request,
.toBinary() no longer works with undefined fields.

sought_game_interactions.ts:71 sr: ...
console.js:288 Error
    at assert (assert.js:20:15)
    at writeField2 (binary-format.js:288:5)
    at Object.writeMessage (binary-format.js:108:17)
    at type.toBinary (message.js:75:13)
    at writeMessageField (binary-format.js:377:28)
    at writeField2 (binary-format.js:317:17)
    at Object.writeMessage (binary-format.js:108:17)
    at type.toBinary (message.js:75:13)
    at writeMessageField (binary-format.js:377:28)
    at writeField2 (binary-format.js:317:17)